### ISSUE TITLE
v0.5.0 macOS にてフォント検証で「'post'テーブルの使用性」エラー

### ISSUE THREAD

**Issue by yuru7** [yuru7/PlemolJP#10]
Twitterより。

> PlemolJP、最新の0.5.0はmacOSでフォントを検証に失敗する。0.4.0では問題なし。upstreamの問題だろうか。

引用元: https://twitter.com/matsuu/status/1444458312523599874?s=20

![image](https://user-images.githubusercontent.com/13458509/135738058-d180978c-8c18-48f5-9f6a-5b3362cc17db.png)

**※作者はMacを所有していないため、検証にご協力いただける方は以下をご報告いただき、修正ビルドの検証（解消されたかを確認）にご協力いただければ幸いです。**

- macOSのバージョン
- v0.5.0 をインストールして、同様の問題が起こるか
- 修正ビルドがインストールできるか（修正はこれから対応します）

**Comment by matsuu** [comment]
macOSのバージョンは11.6です。ソフトウェア・アップデートは最新まで適用済。
エラーが出るのはNFだけで、HSや無印では発生しませんでした。

**Comment by uixuaaa** [comment]
- macOS バージョン 10.15.7
- NF 版だけ画像と同じエラーになりました

**Comment by yuru7** [comment]
@matsuu @uixuaaa 
原因と思われる箇所を修正しました。インストールできるようになったか、お試しいただけますか？
ビルドに使用するツールの1つでバージョンを下げたため、NF以外のファミリーにも変更が加わっています。余力があれば、NF以外のバージョンもインストールできるかご確認いただけると大変助かります。
https://github.com/yuru7/PlemolJP/tree/issue10/build_issue10

**Comment by uixuaaa** [comment]
@yuru7 

> https://github.com/yuru7/PlemolJP/tree/issue10/build_issue10

すべてインストールできました。

<img width="631" src="https://user-images.githubusercontent.com/62936713/135745800-f3fa0c8a-f74c-43c4-8078-85e4077def2d.png">

**Comment by matsuu** [comment]
私の手元でもすべてエラーなくインストールできました。

**Comment by yuru7** [comment]
@matsuu @uixuaaa
ご確認ありがとうございました！

原因としては、ビルドに使っているFonttoolsというPythonパッケージのバージョンが上がったことで、フォントファイル内部に持つ post テーブルの持ち方が変わったためと思われます。バージョンを下げたFonttools 3.44.0はPython 2.7で動いており、Deprecated扱いになっているため、いずれはFonttoolsのバージョンアップに対応しなければなのですが、手元にMacが無いためどうしたものか…と考えているところです。

ひとまずは解消されたとのことで、このビルドで後ほどリリースに出したいと思います。
