### ISSUE TITLE
v1.2.0から1:2版の半角英数字の大きさが変わったのは意図した変更でしょうか？

### ISSUE THREAD

**Issue by 1-1-5** [yuru7/PlemolJP#14]
PlemolJP-RegularとPlemolJPConsole-Regularでしか確認していませんが、変更点として書かれていないのが気になったので。

**Comment by yuru7** [comment]
はい、意図的なものです。
なお変更点として書かれていたか、という点で言うと、「1:2幅版のヒンティングを調整しました」という箇所が該当します。ヒンティング付与に使っているttfautohintというツールでは、元となるグリフの大きさに応じて自動でヒンティングの付き方が変わってくるため、その調整のために半角英数字の大きさを微調整しています。
それにより一部の環境、例えばHiDPIモニターの環境下であったり、特定の文字サイズの場合に以前のバージョンよりも半角英数字の大文字 (A-Z) がほんの少し大きくなっているように見えるかもしれませんね。

**Comment by 1-1-5** [comment]
調整の結果とわかり安心しました。
対象文字数も多くて表示に結構影響する部分に思えたので気になって質問させていただきました。
表示上では大きさの変化はわからないけど、線が気持ち太くなってくっきりした印象です。
お答えいただきありがとうございました。
