### ISSUE TITLE
macOS で 等幅フォントとして分類されていません

### ISSUE THREAD

**Issue by henoya** [yuru7/PlemolJP#15]
Hackgen から愛用しています。
私は macOS で使用しているのですが、等幅フォントとして認識されていません。
実用上はほとんど問題はないのですが、ごくまれに等幅フォントのみしかフォント指定できないソフトがあり、フォント指定できない場面がありました。
コードエディターのために、いわゆる等幅フォントをいろいろインストールしているのですが、他のフォントでも等幅と分類されるフォント自体が少ないです。
Source Han Mono 等も等幅にはなっていませんので、macOS の認識条件が特殊なのかもしれません。

本家 IBM Plex Mono は等幅として分類されています。

等幅として分類されているフォント
![image](https://user-images.githubusercontent.com/143017/144691015-8648d769-3799-4a14-9584-f254a9fd5a16.png)

インストールしているフォント(一部)
![image](https://user-images.githubusercontent.com/143017/144691080-43fa8020-d89b-451a-a529-472e7ca4c140.png)

**Comment by yuru7** [comment]
ご報告ありがとうございます。

macOSネイティブのフォント判定で、等幅に分類されていないのですね。

ただ見たところ、他のフリーフォントの多くも等幅判定にはなっていないようですね。おそらく見た目上の問題はないため、他のフォント製作者の間でも気付かれていないのだろうと想像しています。

以下のissueにあるように「35幅版についてはプロポーショナル扱いとした方が良さそうだ」という結論に至ったのですが、通常幅版についてはしっかりと等幅扱いにしていきたいという想いがあります。
https://github.com/yuru7/PlemolJP/issues/7

しかしながら、当方macOS環境が無いため、再現を取ることができず…よろしければ検証にご協力ください。

とりあえず思い当たる箇所を変更したビルドを以下にアップロードしました。
以下は「PlemolJPdev」という名前でインストールされますので、既存のPlemolJPとは競合しないはずです。試していただければ幸いです。
https://github.com/yuru7/PlemolJP/tree/issue15/build

**Comment by henoya** [comment]
遅くなりました。
上記のファイルをインストールしてみました。
添付の画像の通り、等幅として分類されていました。

![image](https://user-images.githubusercontent.com/143017/144786346-fb94d877-9119-4865-9e7b-800da1d68834.png)

**Comment by yuru7** [comment]
ご確認ありがとうございます。
修正箇所が分かったため、次のリリースにて対応したいと思います！

なお、35幅版については従来の等幅とは半角:全角の比率が異なるため、本件でも等幅扱いには設定しないつもりです。悪しからずご了承ください。

**Comment by henoya** [comment]
35版は1:2ではないですからね。リリースお待ちします🙇

**Comment by yuru7** [comment]
本件に対応した v1.2.3 をリリースしました。（様子見中、ということでとりあえずプレリリースで）

ご確認いただければ幸いです！

**Comment by henoya** [comment]
さっそくダウンロードしてインストールしてみました。
無事等幅カテゴリに分類されています。ありがとうございます。
![image](https://user-images.githubusercontent.com/143017/145659815-bc79b20d-fe80-43d7-ab87-2d04b4d58d21.png)

**Comment by yuru7** [comment]
ご確認ありがとうございます。等幅のみ取り扱えるアプリでも使えるとのことで、安心しました。本issueはクローズしますね。

余談ですが、HackGenでもこの対応を取り入れました。macOS用として詰められていなかった等幅の仕様に対応できる機会となりましたので、感謝しております。
