### ISSUE TITLE
英数字が日本語文字に比べて低い

### ISSUE THREAD

**Issue by Hackgets** [yuru7/PlemolJP#16]
英数字が日本語文字に比べて、文字の高さが低いのは何故でしょうか？個人的には大文字のアルファベットと日本語文字が同じ高さの方が読みやすいです。

**Comment by yuru7** [comment]
それは縦長な印象になるのを和らげるためです。
高さを維持して幅を狭めると、縦に長い印象になり、私は読みづらく感じます。
英数字の縦の高さを縮小しない方がよいということであれば、35版はそのようになっているのでお試しください。

**Comment by Hackgets** [comment]
35版では等幅にならなくなってしまいます。IBM Plex Sans JPの等幅半角字形の英数字には窮屈な印象はありません。ただ、明確な理由があってのことだと分かったので、クローズとします。
