### ISSUE TITLE
PlemolJP Console NF v1.2.4で▽が全角になる

### ISSUE THREAD

**Issue by yamam** [yuru7/PlemolJP#17]
PlemolJP Console NF v1.2.4で▼▽等が全角になっています。
UDev Gothic NFやHackGenNerd Consoleでは半角になっていますので、半角にしていただきたいです。

**Comment by yamam** [comment]
☆★も全角になりますが、こちらは半角にすることは難しいでしょうか？
(UDev Gothic NFやHackGenNerd Consoleでも全角でした)

**Comment by yamam** [comment]
▽▼に関してはSKKでの変換時に表示される記号で、全角表示だと以下のように半分しか表示されないからです。
![image](https://user-images.githubusercontent.com/12369962/190837024-ac6adcb8-12b3-4872-80f6-2cc48a2a4737.png)
☆★に関してはテキストエディタで表示したときに半分しか表示されませんが、これらの文字が出現する頻度は高くありませんので優先度は低いです。
![image](https://user-images.githubusercontent.com/12369962/190837130-9a8221b2-423b-4de6-a56c-eeb1c90f2a02.png)

**Comment by yuru7** [comment]
半分しか表示されないこと自体はテキストエディタ固有の問題のように思えますが（East Asian Ambiguous Width の対応が甘い？）、何のテキストエディタをご使用でしょうか？

**Comment by yuru7** [comment]
ご使用になってるOS、テキストエディタとそのバージョンについてお知らせいただけると助かります。

**Comment by yamam** [comment]
OSはWIndows 10 Pro の WSL 2(Ubuntu 22.04)
terminalはwsltty (mintty 3.6.1)
エディタはneovim(v0.8.0-dev-1109-g72e104142)です。
neovimの設定でambwidth=singleとしているため、East Asian Ambiguous Widthは半角表示されます。
PlemolJP Consoleの説明に以下のように記載されているため、East Asian Ambiguous Widthの文字は半角表示が望ましいと思っています。
「矢印記号などの多くの記号が半角で表示されるため、コンソールでの利用や記号類は可能な限り半角で表示したい人にオススメ」

**Comment by yuru7** [comment]
元々Console版ではEast Asian Ambiguous Widthに相当する文字を半角にすることを目的にしていたわけではないですが、もしも本件に対応するならば今回ご報告いただいた記号だけでなく、Ambiguousとして分類されている文字（下記の `A` に分類されているコードポイント）全体を半角化するのが根本的な対応になりそうです。
https://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt

その方向で検討します。

**Comment by yamam** [comment]
ありがとうございます。
East Asian Ambiguous Widthが半角の日本語フォントは以下のものしか見つからなかったので実現されたらありがたいです。
https://github.com/tomonic-x/Illusion

**Comment by yuru7** [comment]
複数のターミナルアプリで、PlemolJPだけでなく自作の他フォントや定番の等幅フォントなどを使い、Ambiguousとして分類されている文字すべての表示状態を見てみました。

Ambiguous文字を一律で半角幅にしてしまうと、文字が潰れてしまって読み取りできない文字が出てきます。読めないフォントはもはや意味をなさないため、Ambiguousを一律半角幅にするというのは厳しいだろうと結論付けました。

では、半角幅に縮めても読み取れる文字や記号類だけを半角幅にすればいいだろうという話にはなるのですが、それを選別し、表示状態をチェックするにはそれなりに時間を取ってやらなければいけなさそうです。したがって、ちょっと直してすぐ適用、というのもなかなか難しいですね。

恐縮ですがしばらくは現状のままとさせていただき、今後の改善の参考とさせていただきます。

**Comment by yuru7** [comment]
今後のためにメモ: Unicode定義から `コードポイント  文字` の一覧に変換するためのスクリプト

```py
import csv


def main():
    with open("ambiguous.txt", mode="rt", encoding="utf-8") as f:
        code_points = {}
        i = 0
        for line in f:
            code_point = line.rstrip("\n").split(";")[0]
            if ".." in code_point:
                for cp in range(
                    int("0x" + code_point.split("..")[0], 16),
                    int("0x" + code_point.split("..")[1], 16) + 1,
                ):
                    code_points["0x{:04X}".format(cp)] = chr(cp)
            else:
                code_point = "0x" + code_point
                code_points["0x{:04X}".format(int(code_point, 16))] = chr(
                    int(code_point, 16)
                )

            i += 1

            # リミッター
            # if i > 10:
            #     break

        with open("out.tsv", mode="w", encoding="utf-8") as f:
            for key, value in code_points.items():
                f.write(key + "  " + value + "\n")


if __name__ == "__main__":
    main()
```

**Comment by yamam** [comment]
ご検討ありがとうございました。
やはり全部となると大変ですよね。SKK使いとしては▽と▼だけは対応して頂けるとありがたいです。(▽の件があったので今はUDev Gothic NFを使っています)

>Ambiguous文字を一律で半角幅にしてしまうと、文字が潰れてしまって読み取りできない文字が出てくるため

というこは、Ambiguousの選定リストに問題がありそうですね

**Comment by yuru7** [comment]
そうですね…気持ちとしては対応したいところなのですが、一方で「英字側フォントを全て適用するのがConsole版」というポリシーをシンプルに保ちたいという思いもあります。
例外的に一部の用途に引っ張られて仕様を変えると、なし崩し的に他のユーザーも各々の個別要望を反映してほしい、と思うでしょうから。
今後、なにか上手い変更理由が見つかれば、そのなかで▼▽を半角幅にするという判断もあるかもしれませんが、現時点では「SKKで使うから」という理由はレアケースと判断せざるを得ず、、、悪しからずご容赦いただければと思います。

> というこは、Ambiguousの選定リストに問題がありそうですね

うーん、元から半角幅でデザインしていれば、もしかしたらもうちょっと見やすくできるのかもしれません。私がやれることはあくまで「全角幅であるものを機械的に半角幅に縮める」ということなので、どうしてもデザインそのままで横幅をｷﾞｭｯ！と縮めた感じになってしまい、表示品質を担保できなかったりします。
それにターミナルやプログラミングで利用される用途を考えると、デザイン用途よりも小さな文字サイズで利用されることが多いと思いますから、「縮小したら文字が読めない...」という状況には結構気を使わなければいけませんね。
「固定幅フォントかつ文字サイズは小さめで利用」という前提をAmbiguous分類は特に意識していないでしょうから、フォント側で容易に半角化対応できないような文字があるのも仕方ないのかもしれません。

**Comment by ryota2357** [comment]
Neovimの0.8にて、`setcellwidths()`という関数が追加されています。
▼▽の文字幅をNeovim側で変更することが可能です。

https://qiita.com/delphinus/items/3c47567e1af13add968e

**Comment by yamam** [comment]
ありがとうございます。
★☆に設定して使ってみます。
カーソル位置の☆は半分になってしまいますが、これはminttyが原因のようです。(gnome-terminalだと問題ない)
![image](https://user-images.githubusercontent.com/12369962/190992258-d39ef4cb-148c-4e3e-bfdc-7b0da9e8b75b.png)

**Comment by yamam** [comment]
久しぶりに試してみたら▽が半角表示になっていました。(v1.7.1)
![image](https://github.com/yuru7/PlemolJP/assets/12369962/3eff2f66-b510-4424-887b-875a08172b0b)

**Comment by yuru7** [comment]
v1.5.0で対応していました。お声がけしておけばよかったですね、すみません。
