### ISSUE TITLE
中国語 繫体字 簡体字

### ISSUE THREAD

**Issue by itagagaki** [yuru7/PlemolJP#18]
世界各国語のだいたいの文字は使えていますが、中国語の文字（繁体字・簡体字）は含まれていないのでしょうか。

**Comment by yuru7** [comment]
合成対象のIBM Plex Mono、およびIBM Plex Sans JPに含まれているグリフは表示されますが、その他の文字は表示されません。
ただ、どのあたりのコードポイントの文字が表示されれば「中国語の文字（繁体字・簡体字）が含まれている」と言えるのか私には判断できませんので確かな回答はできかねるのですが、 「IBM Plex Sans JP」という名前なぐらいですから、日本語グリフが主で、中国語グリフは含まれていない気はします。

ちなみに https://www.ibm.com/plex/languages/ を見ますと、CJKに関しては日本語・韓国語は対応フォントが公開されていますが、中国語のPlexシリーズのフォントは今のところ公開されていないようですね。

**Comment by itagagaki** [comment]
なるほど、情報をありがとうございます。含まれていなさそうですね。
お騒がせしてすみません。クローズさせていただきます。
