### ISSUE TITLE
README等にhomebrewのコマンドを追加する

### ISSUE THREAD

**Issue by ryota2357** [yuru7/PlemolJP#19]
homebrewのcask-fontsにてPlemolJPをインストールできるようにしました。

https://github.com/Homebrew/homebrew-cask-fonts/pull/6300
https://github.com/Homebrew/homebrew-cask-fonts/pull/6301
https://github.com/Homebrew/homebrew-cask-fonts/pull/6302

以下のコマンドでインストール可能です。

```
$ brew tap homebrew/cask-fonts
$ brew install font-plemol-jp
$ brew install font-plemol-jp-nf
$ brew install font-plemol-jp-hs
```

よろしくお願いします。

**Comment by ryota2357** [comment]
font名をplemolとjpで分けた理由はhttps://github.com/yuru7/PlemolJP/issues/13にて今後PlemolKRなどのフォントができた時のためです。

**Comment by yuru7** [comment]
@ryota2357 
ご提案ありがとうございました🙇‍♂️
追記させていただきました。
