### ISSUE TITLE
Nerd fontsのコードポイントが移動する

### ISSUE THREAD

**Issue by kyoh86** [yuru7/PlemolJP#21]
https://www.nerdfonts.com/releases

Nerd fontsの一部の文字（`F500` - `FD46`）のコードポイントが移されます。

> ### Material Design Icons
> The Material Design Icons have to move codepoints. Historically we patch them in between `F500` - `FD46`; but part of that range is needed for Chinese and other glyphs. With #773 and Plan 5+ of #365 their new home will be after `F0001`. And they grow considerably.
> 
> The v2.3.x release has both, the ‘old’ and the ‘new’ codepoints to enable you an easier transision. Please change already now your prompts and other uses to the new codepoints. Release v3.0.0 will finally drop the old codepoints (`F500` - `FD46`).

最新版ではすでに移動先のコードポイントにすでに各文字が割り当てられ、
移動前の文字についてはobsoleteとしてマークされています。

![image](https://user-images.githubusercontent.com/5582459/220374461-29e21be4-aeab-40ca-9b6f-6ffd6595808c.png)

対応のタイミングは手間の少ないところを狙う形になるかとは思いますが、いずれ対応したほうが良いかもしれません。

**Comment by yuru7** [comment]
情報ありがとうございます。

引用していただいている通り、NerdFonts v3.0 でCJKコードポイントを避けるようにグリフの再配置を行うことで、現状の「一部のコードポイントの漢字グリフとNerdFontsグリフが衝突する問題」が解消されるようです。
今のNerdFontsにおける「`F500` - `FD46` と `F0001～` で同じ見た目のグリフが存在する」状態はメジャーバージョンアップを控えた過渡期の対応のようですので、まだなんらかの変更がかかる可能性があると思われ、追随するのが大変なので一旦は様子見です。

`F0001～` のグリフもv3.0で増えそうですし、 基本方針としてはv3.0のリリースを取り込む際に、

- 今の非推奨グリフ `F500` - `FD46` を削除 (これに伴い NFJ 系列のフォントファミリーは同梱を終了する)
- `F0001～` を新たに取り込む

という対応で考えています。
(v3.0のリリースがあまりに遅くなるようなら、一旦 `F500` - `FD46` と `F0001～` の両方を取り込むのも検討するかもしれませんが…)

ref: https://github.com/yuru7/HackGen/issues/43

**Comment by yuru7** [comment]
[v1.6.0](https://github.com/yuru7/PlemolJP/releases/tag/v1.6.0) でNF v3.0.0を取り込んだため、クローズします。
