### ISSUE TITLE
罫線素片の一部が全角として扱われている

### ISSUE THREAD

**Issue by gasuketsu** [yuru7/PlemolJP#6]
素晴らしいフォントを作っていただきありがとうございます。

03855ec にて罫線素片とブロック要素の半角化の対応をされているかと思いますが、
一部の罫線素片がまだ全角として扱われているようです。

以下のスクリーンショットはv0.2.2で確認したときのものですが、
`U+256D` `U+256E` `U+256F` `U+2570` が全角扱いされていることで罫線がずれているようです。

![image](https://user-images.githubusercontent.com/15703757/129815247-20666c83-b2c9-40e1-92c0-1d3c6b264afb.png)

**Comment by yuru7** [comment]
ご報告ありがとうございます。

罫線素片の半角化ですが、元々 IBM Plex Sans JP のUnicode規定外領域に含まれていた半角の罫線記号を流用することで実現していました。当該領域をすべて流用しているものの、元々 `U+2500-254B` の罫線記号しか用意されていないため `U+256D-2570 ` は IBM Plex Sans JP の全角グリフがそのまま使われてしまっていることが原因です。
![image](https://user-images.githubusercontent.com/13458509/129823142-ee48e728-0493-4530-b7f1-94cabfcf1ab2.png)

対策を検討しておきます。

**Comment by yuru7** [comment]
修正したビルドを以下にアップしました。
しばらく検証してからリリースに掲載しようと考えていますが、検証にご協力いただける場合はお試しください。
https://github.com/yuru7/PlemolJP/tree/issue6/build

**Comment by gasuketsu** [comment]
早速の対応、ありがとうございます。
手元の環境ではまだ `U+256D` ~ `U+2570` 及び一部の罫線素片しか確認していませんが、ズレは解消されており問題無さそうです。

![image](https://user-images.githubusercontent.com/15703757/129858860-72ffe79e-6b41-4557-ad93-e266f3e100ee.png)
![image](https://user-images.githubusercontent.com/15703757/129860159-e99f1cb8-dcc8-4a41-9576-5a90181c1ca9.png)

**Comment by yuru7** [comment]
本件修正を加えた v0.3.0 をリリースしましたのでクローズします。ご報告ありがとうございました🙇‍♂️
