### ISSUE TITLE
Visual Studio Codeで括弧やクォーテーションを使うとカーソルがずれる

### ISSUE THREAD

**Issue by hkcomori** [yuru7/PlemolJP#8]
美しいフォントをありがとうございます。

PlemolJP ConsoleをVSCodeで使用しています。
括弧やクォーテーションを使うとカーソルと文字の表示がずれることがあります。
VSCodeの言語は、PythonとCで発生することを確認しました。

![image](https://user-images.githubusercontent.com/11016036/130005929-c341104b-d94d-4c47-b0ec-42a2d861b50d.png)

一方、メモ帳で同じ内容を同じフォントで表示しても、ずれることは無いようです。

![image](https://user-images.githubusercontent.com/11016036/130006677-1e4577f6-1714-4fd5-95fe-6bd7c0065c16.png)

VSCodeのフォント設定は以下のとおりです。
フォントサイズをメモ帳に合わせて12としても、改善しませんでした。

```json
{
  "editor.fontSize": 14
  "editor.fontFamily": "'PlemolJP Console', Consolas, 'Courier New', monospace"
}
```

解決方法、または追加で調査すべき事項等があれば、ご教示いただけないでしょうか？

#### フォント

PlemolJP Console v0.2.2

#### OS

Windows 10 Pro 64bit 1904

#### VSCode

バージョン: 1.59.0 (user setup)
コミット: 379476f0e13988d90fab105c5c19e7abc8b1dea8
日付: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by yuru7** [comment]
ご報告ありがとうございます。

VSCodeで提示いただいた設定にしてみましたが、残念ながらこちらでは再現できませんでした。
しかし事象を引き起こしている可能性のある箇所を見つけたので、それを修正したビルドを用意しました。以下のバージョンで改善されるか、ご確認いただけますでしょうか？
※次期バージョンに加えようとしている、全角スペース可視化の形状変更も入っていますがご了承ください。
https://github.com/yuru7/PlemolJP/tree/issue6/build_issue8/PlemolJPConsole

ちなみに修正したのは、半角クォーテーション（シングル/ダブル/バック）、カンマ、ドット記号の幅設定です。これらの幅が規定よりも少しだけ広くなってしまっていました。
これは、頂いたキャプチャでもよーく見ると見て取れます。3行目の `({'': '', '': ''})` の末尾の閉じ括弧の位置を2行目と比べると、メモ帳での表示の方が少し右側に来ています。

**Comment by hkcomori** [comment]
VSCodeで試してみましたが、解消されませんでした。

メモ帳でも確認したところ、半角クォーテーションの幅が確かに広いようです。
（以下は全行同じ文字数です。）

![image](https://user-images.githubusercontent.com/11016036/130032365-afb6996d-525e-41c4-a4ee-c0af4b54657c.png)

VSCodeやメモ帳は、再起動してから上記の確認を行いました。

#### PlemolJPConsoleのバージョン

Windowsの設定で、フォントのバージョンを確認した限りでは、バージョンアップは反映されていると思うのですが・・・

![image](https://user-images.githubusercontent.com/11016036/130032525-4ce550e0-4b43-4037-aef2-e79726bb3f98.png)

**Comment by hkcomori** [comment]
大変失礼しました。

Windowsごと再起動すると、解消されました。
Windowsを再起動しないと、フォントの更新は反映されないのですね。
（追加は反映されるので、Windowsの再起動は不要と思っていました）

![image](https://user-images.githubusercontent.com/11016036/130035138-df008256-bde1-4f33-bf54-73268c104e89.png)

**Comment by yuru7** [comment]
> Windowsごと再起動すると、解消されました。

ご確認ありがとうございます！

参考まで、Windowsのフォントファイルの上書きは動きが微妙（中途半端に古いファイルが残ったりする）なので、私は以下のように更新しています。

1. 対象のフォントを使っているアプリケーションを全て終了する
2. ファイル名を指定して実行から `shell:fonts` を指定して実行 （`C:\Windows\Fonts` が開きます）
3. 対象のフォントを選択して削除
4. 対象フォントのアップデート分をいつも通りインストール

一応の確認ですが、メモ帳の幅とVSCodeでのカーソルのズレ、共に解消されましたでしょうか？

**Comment by hkcomori** [comment]
情報不足ですみません。
先程のSSは、メモ帳の幅を示したもので、解消されております。
また、VSCodeのカーソルのズレも、以下の通り解消されております。

![image](https://user-images.githubusercontent.com/11016036/130047921-1d0f6fdf-fe0f-45ab-bc7e-0f70ba85e5ba.png)

フォントの上書き方法のご教示まで、ありがとうございます。
次回はその方法も試してみます。

**Comment by yuru7** [comment]
確認ありがとうございました。
いずれも解消されたとのことで、次のバージョンにこの修正を取り込みたいと思います。

ご協力ありがとうございました🙇‍♂️

**Comment by yuru7** [comment]
本件修正を加えた v0.3.0 をリリースしましたのでクローズします。ご報告ありがとうございました🙇‍♂️
