### ISSUE TITLE
IBM Plex Mono V2.3の取り込み

### ISSUE THREAD

**Issue by gasuketsu** [yuru7/PlemolJP#9]
派生元のIBM Plexからv6.0.0がリリースされました。

[IBM Plex v6.0.0のリリースノート](https://github.com/IBM/plex/releases/tag/v6.0.0) によると
v6.0.0に収容されている IBM Plex Mono V2.3にて、罫線素片などいくつかグリフが追加されているようです。

現在のPlemolJPで、IBM Plex Monoに含まれていないことグリフについてIBM Plex JPのグリフを利用していた物もあったと思うのですが、IBM Plex Monoに新たに追加されたグリフについて、IBM Plex Monoのグリフをそのまま利用するように対応する予定はあるでしょうか？

**Comment by yuru7** [comment]
情報提供ありがとうございます。

ソースフォントをIBM Plex Mono V2.3に差し替えた、v0.5.0をリリースしました。（検証もそこそこにリリースしているため、ひとまずプレリリース扱いです）
お試しください！
https://github.com/yuru7/PlemolJP/releases
